### ISSUE TITLE
prompt to download keys?

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#1492]
Another twist on proving key management...

Instead of failing in this way:

```
(monitor.ml.Error
 (594230aa-622f-3dd7-b3c5-97713d5429f2
  (monitor.ml.Error
   (Failure
     "Transaction_snark: load failed on (/var/lib/coda/2dc36d126be736b5f2a1db13b5243663_verification\
    \n /tmp/coda_cache_dir/2dc36d126be736b5f2a1db13b5243663_verification)")
```

We should prompt the user: Do you want to download keyset "2dc36d126be736b5f2a1db13b5243663" and then go grab the needed keys off s3/gc/etc..

Potential fix:
Have key hashes harcoded in builds and a way to query which they are

**Comment by jkrauska** [comment]
@Schmavery also had some thoughts about how one might do this for the desktop wallet -- ideally we find some code/method reuse for the cli tools too.  (PVKeySync?)

**Comment by bkase** [comment]
`coda client list-required-keys` gives you identifiers for keys that you need such that, a CLI user could go and download them manually and the wallet can automatically download it.

**Comment by bkase** [comment]
If we don't fix this, for CLI users they will just read a stack trace. For UI users, we'll have to hardcode the URLs

**Comment by johnwu93** [comment]
Talked with @jkrauska  and @cmr, we thought it would be appropriate to include the verifying keys in the distribution since they are very lightweight. Since the verifying keys have the same name as the proving keys, we can download the proving keys. The GUI should provide a command to do that and visualize it. Likewise, the cli should have a separate procedure for downloading the proving keys. 

Ultimately, we just need a command that shows the names of the verifying keys that we have.

**Comment by psteckler** [comment]
Working on a CLI command for this.
