### ISSUE TITLE
batch send payments not working

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#1978]
Client code has a mode to batch send multiple payments from a single account to many destinations in one operation.

https://github.com/CodaProtocol/coda/blob/master/src/app/cli/src/client.ml#L239-L283

Right now, only one txn succeeds. 

This used to work, but changed when we added validations of transactions before they go in to the transaction pool.

```
$ ./testing/transactions-many.py
Running: coda client batch-send-payments -privkey-path /home/admin/secrets/high0 -daemon-port 8301 /home/admin/batches/batch_transaction.sexp
Result: Successfully enqueued payments in pool
```

but only once succeeds.

**Comment by enolan** [comment]
Yeah, I punted on validating transactions wrt other transactions that are already in the pool, it only checks against the current best tip ledger. I assumed at the time that nothing actually attempted to queue multiple payments from the same account, since `coda client send-payment` doesn't. Ideally we'd fix this at the same time as #1734, but if it's super important I can probably hack something together.

**Comment by imeckler** [comment]
Did @ghost-not-in-the-shell 's PR #1966 fix this or nah?

**Comment by enolan** [comment]
No, he changed the test to send payments from different accounts. This
issue is about sending multiple payments from a single account.

**Comment by cmr** [comment]
I think this works now
