### ISSUE TITLE
Replace src/dune ML file with static dune file

### ISSUE THREAD

**Issue by psteckler** [CodaProtocol/coda#2619]
`src/dune` is using a Jbuilder (read: old) plugin architecture.

Maybe replace with a script to generate static dune-project file with same information.

**Comment by mrmr1993** [comment]
AFAICT there's no improved alternative yet. For now, it might be a nice compromise to
* migrate our optional compilation to dune virtual modules
* use one of these dune scripts to generate a 'config' module dune file with the appropriate virtual modules included, based on the spec

More importantly, this would let us build a maximal base system that's common to all profiles, rather than repeating it in each build, which would be great for total CI time and switching builds.

I've been meaning to talk to Nathan on this; will do next week.

**Comment by psteckler** [comment]
The generated `dune` file has the same list of warnings for all profiles. Couldn't we use a static dune file with a wildcard `_` for the profile? This is what we did in snarky to turn warnings into errors.

There's some other boilerplate in the generate `dune` that could be hard-coded there.

**Comment by mrmr1993** [comment]
Yup, that should work! SGTM
