### ISSUE TITLE
logrotate of code log file isn't working as expected

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#2930]
Currently on clean/new restart coda daemon logs to 
'coda.log.0'

expected behavior would be for the daemon to log to coda.log, and then rotate a coda.log file to a new file (eg coda.log.0) upon hitting some threshold (time/size)

Please review

**Comment by cmr** [comment]
The way https://github.com/CodaProtocol/coda/pull/2797/files does it is it logs to `coda.log.0` and on a size limit (512MB) moves `coda.log.0` over to `coda.log.1` and starts logging again to `coda.log.0`. Do you just want the filenames switched? I'm still not sure how I feel about the daemon appending to the log instead of overwrite but I guess it makes sense.
