### ISSUE TITLE
Make bans less aggressive 

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#3004]
24 hour bans are blocking users from participating in testnet when they need to restart or when they crash.

Option 1:
Don't actually ban at all, only log condition, do not remove from peer list.

Option 2:
Exponential increase in ban periods.
First ban trigger, 1hour ban
Second ban trigger, 2hour ban
4h, 8h, etc.
maybe as a function of slot time?  30 x slots ^ occurrence

**Comment by jkrauska** [comment]
Asking all users to manually unban a person isn't a good solution.

**Comment by cmr** [comment]
I discussed this with Brandon, who feels very strongly we should turn bans off for now. We need to balance three things:

1. User experience of testnet participants
2. Finding bugs that lead our software to ban itself when participating honestly
3. Mitigating malice

Brandon thinks `3` is just not important for these first testnets, and that we should reactively turn banning on after our network has been attacked once, instead of proactively having bans now. I weakly  disagree, but I do agree that testnet participant UX is very bad and we should prioritize that in the short term.

The task is then to improve the UX without impairing our ability to detect and act on bugs that result in trust actions. Right now we only learn about bans if users come and tell us (although we can certainly look in our own logs for bans). Since we're running a small (and shrinking) proportion of the network, it's certainly possible that there are bans we can't see. 

https://github.com/CodaProtocol/coda/issues/3013 proposes a protocol tweak that helps improve `1`: instead of just closing connections from banned peers, we tell them they are banned. In practice I think this would mean returning an appropriate `Error.t`. Most of our RPCs already have an `Or_error.t` in their response type. Another possibility is to send peers an RPC when we ban them, telling them that we've banned them. Either way, the responsibility of an honest protocol participant is to not send RPCs to a peer that reported a ban until after the ban expires. I think this is something we could ship mainnet with.

To help further `2`, we discussed running a centralized "ban collector". The idea here would be to send a message to the ban collector _instead_ of actually banning the peer. This keeps new users on the network at the expense of removing all our DoS protection. I'm not sure exactly what we should collect. There are both privacy considerations (should we remove or anonymize IPs?) and utility considerations (just the trust action alone isn't very useful for us, it's most useful with logs). The service should be some simple HTTP thing, nothing complex.

**Comment by cmr** [comment]
Another possibility that might be palatable: turn down ban time to like 10 minutes or something.

**Comment by knarz** [comment]
Given that the current p2p protocol is temporary and many users might experience frequent crashes/restarts, scaling down it down to just a fixed hour seems like the simplest solution.

I don't know how the banning interacts with peer discovery, i.e. if banned peers are included when advertising, but with the network being as small as it is, people might end up being isolated easily.

**Comment by enolan** [comment]
Everyone knows my position, but I'll restate anyway. Adding security-compromising hacks is dangerous. "Temporary" solutions become permanent, people forget, and it's hard to tell whether code is doing the right thing.

I'd be OK with some combination of:
* #3013
* turning ban times down to an hour - all we're doing here is making the attacker expend the resources to get a new IP, and the denial of service type attacks that the trust system is supposed to prevent cost the target much less than a new IP.
* Adding a hack, but committing to posting an embarrassing story about / photo of @bkase on the company Twitter if it isn't removed in 30 days. I'm like 90% serious about this one.

**Comment by cmr** [comment]
@bkase ready to put your reputation where your mouth is? ;)

**Comment by imeckler** [comment]
After discussion, let's create an `--no-bans` flag which doesn't ban anyone with the `[@expires_after]` ppx. @psteckler knows about the PPX.

**Comment by bkase** [comment]
Is the expires after a sufficient compromise? I don’t think 30 days is long enough such that all the bugs causing bans would be gone, but maybe we do 30 days and then we re-evaluate how much longer we need when it expires?

**Comment by psteckler** [comment]
I'll make it expire on September 9, when I'm back from vacation. :-)

**Comment by psteckler** [comment]
There was a bug in #3043. Fix is in #3054.
