### ISSUE TITLE
Bootstrap eagerly / request best tip from peers on startup

### ISSUE THREAD

**Issue by imeckler** [CodaProtocol/coda#3028]
Right now we wait until we hear a block to initiate bootstrap. Instead, we should query a peer for their best tip and bootstrap to that. This needs to be carefully examined for correctness, but should be a fine workaround in the short-term.

**Comment by ghost-not-in-the-shell** [comment]
Here's a more detailed description of eager bootstrap:

when we start coda-daemon, instead of passively waiting for a network transition to tell us the current state of the network, we should sample the best tips from some random peers. And then we pick the best one. This best tip would tell us whether we need to do bootstrap or catchup.

**Comment by nholland94** [comment]
https://github.com/CodaProtocol/coda/issues/3174 and https://github.com/CodaProtocol/coda/issues/3173 are followup issues on this work. The main portion of this was completed in https://github.com/CodaProtocol/coda/pull/3112.
