### ISSUE TITLE
Figure out what all of the problems in holy grail test are

### ISSUE THREAD

**Issue by imeckler** [CodaProtocol/coda#3085]

**Comment by ghost-not-in-the-shell** [comment]
After fixing 3 bugs. I noticed that now holy_grail is almost always fails in the same way:

when 1 node disconnects and re-connects again later, other nodes fail to add this bootstrapping/catchup node back. Also I didn't see any logs from this node.

In `gossip_net.remove_peer`, I see this comment:
```
  (* remove peer from set of peers and peers_by_ip

     there are issues with this simple approach, because
     Kademlia is not informed when peers are removed, so:

     - the node may not be informed when a peer reconnects, so the
        peer won't be re-added to the peer set
     - Kademlia may propagate information about the removed peers
        other nodes
  *)
```

This could be one of the problems.

**Comment by ghost-not-in-the-shell** [comment]
A problem I find is that in holy grail: after 1 proposer is offline, when it comes back online again, it won't produce block somehow.

**Comment by ghost-not-in-the-shell** [comment]
One of the issue is that when nodes are in the first epoch, we would always start transition frontier phase. This means even though a peer is out of sync, it could also propose blocks and send it to the network, which would cause the network to ban it.

A simple fix is to delay the bootstrap of a proposer until the first epoch has passed. But the same scenario could happen in the real world, so I don't know if we would accept such a hack.

**Comment by ghost-not-in-the-shell** [comment]
Another possible failure reason for holy-grail: #3282
