### ISSUE TITLE
[Bug] Block Production slows as Transaction Rate Increases

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#3416]
The first `golden hour` occurred this morning, and lead to block height ceasing to increase for ~3 hours. 

This is a graph of blocks proposed sorted by their parent block. 36 blocks were proposed on top of block `163`. Once some internal state caught up, block production returned to normal. 

<img width="1120" alt="Screen Shot 2019-09-11 at 2 17 26 PM" src="https://user-images.githubusercontent.com/2635475/64738851-455e2180-d4a5-11e9-9107-2884abe786c7.png">

**Comment by yourbuddyconner** [comment]
This graph is the Block Production rate at 5-minute intervals (roughly every slot). 

The rate of production has been pretty constant throughout this event, possibly pointing towards some consensus parameters that need to be tuned. 

<img width="1045" alt="Screen Shot 2019-09-11 at 3 10 22 PM" src="https://user-images.githubusercontent.com/2635475/64739213-4d6a9100-d4a6-11e9-8a00-2754ed77fdf5.png">

**Comment by yourbuddyconner** [comment]
Block production by Host: 
<img width="1085" alt="Screen Shot 2019-09-11 at 3 28 15 PM" src="https://user-images.githubusercontent.com/2635475/64740138-2f526000-d4a9-11e9-957e-a161d3fe574b.png">

**Comment by yourbuddyconner** [comment]
@jkrauska noticed that blocks were only being chosen from one block producer, so one producer was restarted and its blocks began to be chosen again. This might indicate something amiss with the internal state of a producer that gets reset when it is restarted. 

![screencapture-codaexplorer-garethtdavies-2019-09-11-16_39_08-2](https://user-images.githubusercontent.com/2635475/64743105-69c0fa80-d4b3-11e9-9fdc-ce89fffa978d.png)

**Comment by yourbuddyconner** [comment]
This is a graph of "Useful Gossip (external transitions)": 

<img width="1205" alt="Screen Shot 2019-09-11 at 4 56 14 PM" src="https://user-images.githubusercontent.com/2635475/64743543-3a12f200-d4b5-11e9-844a-b8df0310727c.png">


https://search-testnet-djtfjlry3tituhytrovphxtleu.us-west-2.es.amazonaws.com/_plugin/kibana/app/kibana#/discover/f275ac10-d4e8-11e9-b1f9-bb4ea8c68935?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(message,agent.hostname,metadata.peer,metadata.transition.protocol_state.body.consensus_state.blockchain_length),filters:!(),index:'4cb11720-adb9-11e9-a438-dbd7f50e05cf',interval:m,query:(language:kuery,query:'%22Trust_system.Actions.Sent_useful_gossip%20(external%20transition%20$state_hash)%22'),sort:!('@timestamp',desc))

**Comment by enolan** [comment]
was cpu usage pegged perhaps?

**Comment by yourbuddyconner** [comment]
<img width="1451" alt="Screen_Shot_2019-09-11_at_5_03_24_PM" src="https://user-images.githubusercontent.com/2635475/64743813-39c72680-d4b6-11e9-8428-30912b86ef4b.png">
Not particularly

**Comment by deepthiskumar** [comment]
The root cause of this is an invalid transaction snark in the snark pool of the block producers. Currently we do not verify incoming transaction snarks from snark workers before adding them to the snark pool. They get verified when creating/validating a block. If any transaction snark fails to verify then blocks don't get produced/accepted,

The 36 blocks being proposed on top of block`163` were mere attempts and eventually failed with the error: `Error building breadcrumb from proposed transition. Invalid staged ledger diff -- Verification failed for proof` for including invalid snarks. O1's snarks costed more and probably other snark workers' as well and therefore, could not replace the invalid transaction snark that was already in the snark pools of the block producers.

The spell broke when one of the block producers crashed (#3433) losing all the transactions and snarks in its pool. When restarted, it began producing empty blocks. Later, other block producers were manually restarted producing more empty blocks.
There were no transactions being included in any of the blocks until some new snark workers broadcasted their snarks.

o1 snark coordinator was also restarted during this period but for some reason they were not being broadcasted as suggested by the log message printed during block production: `Number of proofs ready for purchase: 0`. Snark coordinator logs are all overwritten by the excessive "Waited too long" messages and therefore are not very useful

**Comment by imeckler** [comment]
This ought to be fixed since invalid proofs are now rejected.
