### ISSUE TITLE
incorrect base58 conversion of public key in develop

### ISSUE THREAD

**Issue by deepthiskumar** [CodaProtocol/coda#3446]
```
let pk = Signature_lib.Public_key.Compressed.of_base58_check "tNci9ERxHGkemqBmNxEWTcPgY5sn347yq6BFcUGTpve6aJpaDUgaaTEQ3rfAgYeK7KhzEbYoJvSbqQ8u88aBNtu8ALVcEeRo4ei6sGjxMsmBAJW7vwW57KLzrvou4YEMA3saq6Xqtpg3sb" |> Or_error.ok_exn
in 
Core.printf !"base58: %s" (Signature_lib.Public_key.Compressed.to_base58_check pk)
```
prints `8QnLYyB9MWzJfcaaD3KLf6REBuV3FavrsdKi7Nv9KvjyXysz8Lsvuzcvdxjs1Et3bk`

The pk string is from client status  which does Signature_lib.Public_key.Compressed.to_base58_check ( https://github.com/CodaProtocol/coda/blob/724dd2444eeece3a4ece89d0d98e1bf06d5bac65/src/lib/coda_commands/coda_commands.ml#L271 )

This is working fine in master (or at least until 92a3c1eaa0ebbd2d8403edf8ec58c3d77faa21cf)

**Comment by enolan** [comment]
It almost *has* to be 2a9ba99324e429a24033c680d649f0698b8c51a1#diff-6fdf53f6221f802078178972a5e656d4 but I didn't change anything about the compressed representation there.

**Comment by psteckler** [comment]
Not a bug: the input key is from a med curves build, while the `of/to_base58` functions here were being run in a small curves build.

This could have been caught in snarky, I believe, since the serialized data for the `field` component of the key was the wrong length.

In particular, here: https://github.com/o1-labs/snarky/blob/master/src/libsnark.ml#L834
I think we have the invariant that `length_in_bytes` is the same as the input array length.

@mrmr1993 is looking at putting in an exception or similar.

**Comment by psteckler** [comment]
Confirmed there's a size invariant at that location, even when the `field` is in the middle of a data structure.

**Comment by imeckler** [comment]
Maybe have some kind of byte that IDs which curve the pubkey belongs to.
