### ISSUE TITLE
coda crashed and said to report it

### ISSUE THREAD

**Issue by cbrown330** [CodaProtocol/coda#3492]
I noticed that each time i ran the  {coda daemon -peer filet-mignon.o1test.net:8303} command i would get an error saying the daemon was not running on port 8301.  Figured this was odd cause i just told it port 8303.  so went in the daemon help list and ran the command

coda daemon -client-port 8302 << i set the TCP port out of my router as 8302

when i ran it i got the following 

codo@codo-node:~$ coda daemon -client-port 8302
2019-09-25 22:45:58 UTC [Info] Coda daemon is booting up; built with commit "92a3c1eaa0ebbd2d8403edf8ec58c3d77faa21cf" on branch "master"
2019-09-25 22:45:58 UTC [Info] Booting may take several seconds, please wait
2019-09-25 22:45:58 UTC [Info] OCaml memory statistics
2019-09-25 22:46:07 UTC [Warn] long async cycle 7.015615735s
2019-09-25 22:46:18 UTC [Info] Starting Bootstrap Controller phase
2019-09-25 22:46:18 UTC [Info] Coda daemon is now connecting
2019-09-25 22:46:18 UTC [Info] Pausing block production while bootstrapping
2019-09-25 22:46:18 UTC [Info] Attempted to turn on snark worker, but snark worker key is set to none
2019-09-25 22:46:18 UTC [Info] Daemon ready. Clients can now connect
2019-09-25 22:46:18 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: "(monitor.ml.Error\n  (Unix.Unix_error \"Address already in use\" bind\n    \"((fd 56) (addr (ADDR_INET 0.0.0.0 8302)))\")\n  (\"Raised at file \\\"src/fd.ml\\\", line 272, characters 18-27\"\n    \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 170, characters 6-47\"\n    \"Caught by monitor Tcp.close_sock_on_error\"))"

  ☠  Coda daemon crashed. The Coda Protocol developers would like to know why!

  Please:
    Open an issue:
      <https://github.com/CodaProtocol/coda/issues/new>

    Briefly describe what you were doing and attach the crash report /home/codo/.coda-config/coda_crash_report_2019-09-25_22-46-18.277755.tar.gz

**Comment by Schmavery** [comment]
I think `coda daemon -client-port` might not be what you want.
There are a few different ports involved here.
- There's the port of your peer that you're connecting to: 8303 (from filet-mignon.o1test.net:8303)
- There's your external TCP port, which by default is set to 8302 (you mentioned you port-forwarded this)
- There's a local RPC port that we use to communicate with the daemon from the CLI, by default this is 8301 (this is what -client-port changes)
- (There's also the UDP port used for peer discovery, which you probably had to portforward, on 8303, and a rest server running on 3085, but those shouldn't affect this)

Maybe you can give some more detail on how you ran into the error saying "the daemon was not running on port 8301". Usually that happens when you run something like `coda client status` when the daemon is not running or if you run it before the daemon prints out the `Clients can now connect` message.
If I had to guess, this `Address already in use` crash happened because either you're already running a daemon somewhere, or the TCP port is conflicting with the RPC port when you use `-client-port` to make them the same.

**Comment by cbrown330** [comment]
That’s absolutely correct came to find out that the daemon was not running.  I believe I am having port issues here but my network at the house is not an average one I guess. Not for the US. I don’t use my ISP provided router. I put it in pass through mode and use my personal Blackhawk.

I am not sure if this is what is preventing me to get out or not. But I am about to TCP from the outside and see.

I more coder then network lol. If anything I’ll get my IT guy at work to take a spin at it tomorrow. Thx guys

Sent from my iPhone

On Sep 25, 2019, at 7:30 PM, Avery Morin <notifications@github.com<mailto:notifications@github.com>> wrote:


I think coda daemon -client-port might not be what you want.
There are a few different ports involved here.

  *   There's the port of your peer that you're connecting to: 8303 (from filet-mignon.o1test.net:8303<http://filet-mignon.o1test.net:8303>)
  *   There's your external TCP port, which by default is set to 8302 (you mentioned you port-forwarded this)
  *   There's a local RPC port that we use to communicate with the daemon from the CLI, by default this is 8301 (this is what -client-port changes)
  *   (There's also the UDP port used for peer discovery, which you probably had to portforward, on 8303, and a rest server running on 3085, but those shouldn't affect this)

Maybe you can give some more detail on how you ran into the error saying "the daemon was not running on port 8301". Usually that happens when you run something like coda client status when the daemon is not running or if you run it before the daemon prints out the Clients can now connect message.
If I had to guess, this Address already in use crash happened because either you're already running a daemon somewhere, or the TCP port is conflicting with the RPC port when you use -client-port to make them the same.
