### ISSUE TITLE
[Feature Request] Metrics for TPS

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#3617]
@nholland94 Mentioned that the metric `Coda_Transition_frontier_finalized_staged_txns` can be used as a proxy for TPS. However, it could be easier to use if "the metric returns to zero as an empty slot passes."

**Comment by ghost-not-in-the-shell** [comment]
It's hard to detect if a slot is empty or not. Because we may not receive the transition at the exactly the slot it generated. Some times we may receive late transitions. We probably could say that the slot is empty after waiting for `delta` slots.

Also `finalized_staged_txns` is a strictly increasing metrics, which is hard to use if you want to estimate TPS for a certain period time. I would recommend using `recently_finalized_staged_txns`. I think `recently_finalized_staged_txns` + rolling_window could give us a more accurate account of TPS.
