### ISSUE TITLE
[Python] Update python scripts to be python 3.6+ compatible 

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#3666]
There's several python scripts written in Python 2.7 that should be updated. Additionally, while this is being done, we should standardize the `#!` in each of these files to be consistent. 

I'd also recommend we install `https://github.com/google/yapf`and standardize a script naming format (`-` vs `_`) etc.

**Comment by psteckler** [comment]
Maybe helpful: https://docs.python.org/3/howto/pyporting.html

**Comment by cmr** [comment]
I think we should hashbang plain system python and have all our scripts compatible with both 2 and 3. It's an awful user experience to have the "wrong" python, or not have the right python available. https://pypi.org/project/six/ is helpful for papering over some discrepancies. Otherwise, we should migrate to 3 entirely and pick that for our hashbang.

**Comment by imeckler** [comment]
If you run
```
sudo apt install ag && ag 'print ' -G '.*\.py'
```

you can find them all

**Comment by enolan** [comment]
We can avoid having to deal with different Python versions entirely by
running everything with a nix-shell shebang. Let me see if I can get an
example running.

**Comment by enolan** [comment]
So it works for everything that doesn't try to build Coda AFAICT. If you
run `test.py` in a nix-shell environment it will try to build Coda using
the Nix toolchain and libraries that are in scope, and things break when it
links against the non-nix object files you've already compiled into
`~/.opam`. I might be able to get it to use the host system, would have to
look into it some more.
