### ISSUE TITLE
Signalling -- Add 32 byte string to external transition

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4199]
There should be two strings
1. current version
2. desired upgrade version

Plus CLI for setting the string (shasum a thing?)

Use the thing we already have for memos that knows how to do SHA or plaintext

**Comment by psteckler** [comment]
@bkase @imeckler the strings represent protocol versions, using some symbolic name? Or a digest of something?

Are the two strings compile-time constants? Or just the current version, and the desired version defaults to the current version, but can be overridden in CLI?

**Comment by imeckler** [comment]
@bkase Is there any reason we can't just have a single string which is desired upgrade version?

**Comment by imeckler** [comment]
@psteckler I believe the idea was for them to be git SHA hashes.

I think for now maybe just make them be configured on CLI, with default being all \000 or something and we can figure out the specifics of this later.

**Comment by imeckler** [comment]
@nholland94 has suggested the following:

Initial Hard Fork Signaling Work
================================

# Additional Node State

Every node now must track what fork id it is currently operating on. The initial value for this can be fed in first time on the CLI, and then it should probably be cached in the config directory for reuse on future runs (the persistent content in the config directory is essentially scoped to the fork id, so we may not want to allow users to switch to another fork id with the same persitent content). In the future, the node may update this value, but we do not need to implement that for the initial pass of this work.

# Additional Block Fields

2 new fields will be added to the block: `current_fork_id`, and `next_fork_id`. A format will need to be chosen for the fork_id representation which will allow a reasonable number of values that can be selected. Something as simple as a 4-character string will likely suffice.

# Additional Block Validation Logic

A node should only accept and rebroadcast blocks which have a matching `current_fork_id` to the nodes current fork id it is operating on. If a block is received with a different `current_fork_id` than what the node is operating on, the node should instantly ban the sender of that block (since we presume no messages coming from them will be relevant to us). This logic applies to not only block intake, but additionally to other areas of the application where the block is validated (such as bootstrap and catchup). As such, validating the fork id should be folded into the `Block.With_validation` abstraction as a new validation step which *cannot* be skipped.
