### ISSUE TITLE
[CRASH] Assert_failure src/lib/network_pool/indexed_pool.ml:529:8

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#4296]
Not quite sure what's up with this one, it shows up periodically. 

```
(monitor.ml.Error "Assert_failure src/lib/network_pool/indexed_pool.ml:529:8"
  ("Raised at file \"src/lib/network_pool/indexed_pool.ml\", line 529, characters 8-69"
    "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 531, characters 30-193"
    "Called from file \"src/lib/network_pool/network_pool_base.ml\", line 26, characters 15-65"
    "Called from file \"src/pipe.ml\", line 827, characters 4-56"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
    "Caught by monitor coda"))
```

**Comment by imeckler** [comment]
@deepthiskumar and @nholland94 have a theory of what's up here

**Comment by ghost-not-in-the-shell** [comment]
After some investigating, I think this bug is mainly caused by an async race condition in transaction_pool.

There are two separate processes trying to update the transaction pool object in two different ways. Specifically,
1. every transaction_pool_diff that comes from the network would trigger an update for the pool through `Resource_pool.Diff.apply` function
2. every best_tip_diff that comes from the transition frontier system would also trigger a different  update for the pool through `handle_diff` function

If `apply` overwrite the result of `handle_diff` then there are chances the system would die with the above bug.

--------
There's  another possible reason for this bug:
Because the assertion would take a look at the nonce at best_tip_ledger, and best_tip_ledger is updated when a best_tip_diff arrives, and best_tip_ledger and best_tip_diff could be mismatch due to the desynchronization nature of the transition frontier extensions. I think this https://github.com/CodaProtocol/coda/issues/4157 would fix it.

**Comment by imeckler** [comment]
@deepthiskumar 's upcoming PR should fix most of the transaction pool issues including what @ghost-not-in-the-shell mentions above. There may still be some race-condition related problems which will require a higher level change (frontier synchronizaiton) as as described in the second section of @ghost-not-in-the-shell 's comment
