### ISSUE TITLE
Revamp CODEOWNERS to use teams (proposal)

### ISSUE THREAD

**Issue by Schmavery** [CodaProtocol/coda#4743]
### Problems
- Current CODEOWNERS system causes too many people get notified, making it hard to distinguish between the desire for a "codeowner review" and "full review". It can be also hard as the author of the PR to be sure that someone has fully reviewed the change and not just their section.
- Many PRs pull in several sets of reviewers for small changes that do not substantively change the files, requiring the collection of many "rubber stamp" approvals.
- Lists of codeowners easily get out of date 

### Goal
The goal of the codeowners system should be to help the committer find the right person to help review, not assume that the author of the PR is working in bad faith and block them in case the code might be wrong.

- I think we can assume that if the author of the PR knows the best person to review the code (which they usually do), they will add them to the review.

- If the author doesn't know who to add as a reviewer, the CODEOWNERS system should enable them to find the relevant reviewer. It should be made hard for a PR author acting in good faith to accidentally miss an important reviewer.

### Solution
I think we can greatly reduce the granularity of CODEOWNERS file.

With the current size of the eng team, we can probably get away with only 3-4 groups (`product`,  `protocol`, `infra` are one obvious division). We would make github [teams](https://github.com/orgs/CodaProtocol/teams) for these groups and only make those teams CODEOWNERS (with as few exceptions as possible).

> Note: When making a github team a codeowner, the team alias gets added to the `Reviewers` and the PR is blocked on any member of the team approving the code. It would be the responsibility of someone on the reviewing team to assess who would be best to review the change and suggest required reviewers if necessary.

This is part of #4740
cc @bkase

**Comment by yourbuddyconner** [comment]
I think this is a good idea, especially this:
> I think we can assume that if the author of the PR knows the best person to review the code (which they usually do), they will add them to the review.

**Comment by nholland94** [comment]
We may want some more granular teams for the protocol code base. Knowledge of different parts of the code base is currently split up among different groups of developers. For instance, I would not be comfortable being an approving review on txn snark changes, and in turn, I would want either me or someone who has worked a lot with transition frontier to review that code before approvals. Of course, we don't expect devs to have "bad faith" and to still get the correct people to review, but that can be tricky sometimes with PRs that span across multiple key pieces of code. For instance, a PR that touches both networking code and frontier code should not be approved after only a networking-stack aware engineer approves it (vice versa, I don't want it to be unblocked if I approve either because I'm not knowledgable enough on our networking-stack). I will suggest some example subteams for protocol:

- `protocol-networking`
- `protocol-frontier`
- `protocol-ledgers`
- `protocol-staged-ledger`
- `protocol-blockchain-snark`
- `protocol-txn-snark`

These may be too granular, but the idea is that many of these teams will have overlap. If the granularity of this becomes too annoying (as in you need too many reviews to merge still), then the goal would be to focus on more cross-pollination of our team members.

**Comment by bkase** [comment]
For what it's worth, I agree with @nholland94 . It would be a good idea to split up the protocol code like that.

I like the idea of growing the size of each of those sub-areas as more people get familiar with more parts of the codebase.

**Comment by Schmavery** [comment]
Yeah I'm glad to get some more feedback on the protocol side of this, thanks.

The idea was that even if the whole protocol team can't review the entire protocol code base (makes sense), the team is small enough that it doesn't seem unreasonable that the team could get to a point where anyone on the team can know roughly who *should* be looking at the code.

What I've seen a lot of recently (correct me if I'm wrong) is changes that happen to tweak a little thing in many different "regions" of code ownership without necessarily making substantial changes. It seems like it would be nice if someone from the protocol team could review and assess whether someone else should take a look at it.

In your example, a PR that touches both networking code and frontier code, if I'm a protocol engineer reviewing the PR and I only have frontier experience, I'm going to review the entire to the best of 


Maybe something I should have called out more explicitly in my first post should have been changing the culture from "at least one of the reviewers on the PR needs to approve it" to "ideally all/most reviewers on the PR should approve". This obviously requires reducing the number of required reviewers, but has the benefit of making it clear to reviewers that their review is actually needed, so that they don't accidentally block something.


everyone looking at 2 files and no one actually reviewing

**Comment by Schmavery** [comment]
oops

**Comment by nholland94** [comment]
Ok, I buy it (given that our team is small; if we were growing soon, I may feel slightly differently). The only concern left in my head is who is in charge of declaring who needs to approve before a PR is ok to be merged. Seems like that is basically on the shoulders of the PR owner, which seems fine so long as we hold some level of accountability about that decision.

I think we should try this out. We can always revisit some details of the team grouping if issues crop up, but it seems like they probably won't.

**Comment by Schmavery** [comment]
Thoughts:
1 - I think the PR owner is at least partially accountable for this
2 - The team member that approves the code is also accountable for making it clear that the code should be reviewed by another member as well before merging (if that's the case)

**Comment by yourbuddyconner** [comment]
Yeah I very much agree with putting the onus on the PR-opener in this situation. Obviously a list of who to ask is important here too.

**Comment by bkase** [comment]
Very good argument @Schmavery , I'm onboard.

**Comment by bkase** [comment]
Implemented!
