### ISSUE TITLE
Integration Testing: Assert things on events investigation

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4787]
Epic: #4735 

Given that we need structured events for open tracing anyway, we want to reuse that infrastructure for making our assertions in the integration tests.

The plan here is to attempt to use StackDriver as we already have it set up to ingest logs pending the results of the following investigations:

1. Throughput

Can we stream in stack driver logs with minimal filtering and process them fast enough to keep up with realtime with 200 nodes reporting?

2. Latency

How long does it take between a log line emitting in a node to it appearing in the stream on a different node?

Assuming (1) and (2) are confirmed -- this is our mechanism for implementing assertions in tests.

**Comment by nholland94** [comment]
Latency of logs is acceptable, and throughput has been deemed as not significant in the short term. At this point, sounds like we may end up using the automated validation service for consuming structured events as statistics from the network. If we do that, then throughput is not significant issue since we can scale the automated validation service rather easily.
