### ISSUE TITLE
Persist root history

### ISSUE THREAD

**Issue by psteckler** [CodaProtocol/coda#4859]
Capture a window of 2*k blocks preceding the current root.

This task is related to the disaster recovery program described in #4858.

**Comment by aneesharaines** [comment]
Clarification needed:  Are we capturing enough root history already and what format do we save it?

**Comment by deepthiskumar** [comment]
Root history is looked up by `Transition_chain_prover.prove` for delta transition proof (`delta` most recent states) This information can be found in the transition frontier.
Root history is also looked up to service catchup requests. The current rule for bootstrap/catchup is that we do catchup if we are `<= 2k` from the best tip and bootstrap otherwise (@nholland94 / @ghost-not-in-the-shell  do you know why this is 2k and not k?) Hence a node might request states older than k which is available from the root history.
However, for hark fork/disaster recovery, we would be discarding all the states after the root. So, might not have 2k states in the root_history for nodes to be able to catchup. Depending on our approach to deal with nodes that have not upgraded and are trying to catchup, we might have to store 3k nodes in the root_history and when recovering the state for the hard fork, we just use the required 2k?

**Comment by imeckler** [comment]
Subsumed by https://github.com/CodaProtocol/coda/issues/4858
