### ISSUE TITLE
Buildkite CI: Coda unit tests are migrated to dhall-based Buildkite pipeline

### ISSUE THREAD

**Issue by 0x0I** [CodaProtocol/coda#4943]
**Overview:**

With our Continuous-Integration pipeline consisting of the Buildkite coordinator-as-a-service platform and a programmable workflow and pipeline configuration rendering engine based on Dhall becoming more solidified, this task entails supporting the process of migrating over CI jobs from the previous CircleCI framework.

**Goals:**
* [ ] develop dhall->pipeline rendering logic for *test-unit--dev* test suite
* [ ] develop dhall->pipeline rendering logic for  *test-unit--nonconsensus_medium_curves*
* [ ] develop dhall->pipeline rendering logic for *test-unit--dev_medium_curves*

**Comment by 0x0I** [comment]
**References:**
- existing CircleCI pipeline [configs](https://github.com/CodaProtocol/coda/blob/develop/.circleci/config.yml#L572)
- CircleCI resource classes [specifications](https://circleci.com/docs/2.0/configuration-reference/#resource_class) (e.g. small, medium, xlarge)
- Coda protocol toolchain docker image [tags](https://hub.docker.com/r/codaprotocol/coda/tags)

**Comment by bkase** [comment]
Note: All these pipelines are more or less the same, but just build with different profiles. I'm 99% sure @mrmr1993 can show us how we can now build Coda such that we can reuse the same artifact across dev and medium curve versions. The "nonconsensus" one is a build that targets JavaScript so that will definitely have to be rebuilt specifically for this job.

**Comment by bkase** [comment]
Also, I'm going to say this should be around a week of focused work, but please push back if you disagree.

**Comment by 0x0I** [comment]
> Also, I'm going to say this should be around a week of focused work, but please push back if you disagree.

Based on what I've gathered so far, the different *unit* tests  seem verify similar with the differences being:
-  `--profile` ARG pertaining to unit test category
- `DUNE_PROFILE` environment variable based on same category as above
- `bash -c 'source ~/.profile...` test setup

Seems like all 3 could be captured in a single `Jobs/` `Pipeline.dhall` and `Spec.dhall` with a structure resembling the [Lint :: Fast job](https://github.com/CodaProtocol/coda/blob/feature/ci-check-reformat/buildkite/src/Jobs/Lint/Fast/Pipeline.dhall). Feeling like *1wk* would be pretty generous but could be overlooking something.

**Comment by bkase** [comment]
@0x0I We desperately need the vcpus -- the more the better. I suspect CircleCI medium will be way too slow, but it doesn't hurt to try it! For background, I believe we started with medium, but increased slowly until xlarge (what most of the jobs are currently) out of necessity. We definitely don't need the RAM there though.

re: the nonconsensus job -- we compile the same OCaml we use for the other parts of the protocol to JavaScript instead of machine code. You can think of this one as an alternate backend rather than a separate SDK.

**Comment by 0x0I** [comment]
Ha whoops, meant "Medium - 1 wk" in the sense of the Issue Size (based on your previous work estimate comment).

In any case, got it and the *resource class* or instance size the jobs should run on makes sense to me unless proven otherwise with some sort of benchmark. But yea, can definitely see developing or incorporating some sort of benchmarking tool down the line!
