### ISSUE TITLE
Make upload-deb work in the buildkite environment

### ISSUE THREAD

**Issue by lk86** [CodaProtocol/coda#5282]
Parallelizable task 1 from: https://github.com/CodaProtocol/coda/pull/5277

Requires porting the existing upload-deb script to a solution that is independent from circle-ci variables/environment.

**Comment by bkase** [comment]
Specifically, we want `make publish-deb` or the `./scripts/publish-deb.sh` to "work" on buildkite. I define "work" as: When a master artifact build executes, it updates the `--codename release` deb package. Otherwise, it updates `unstable` (we don't need the other channels in my opinion).

This script does much more than we need it to now, so it probably is best to rewrite it. We can assume we'll only run it during the proper artifact job.

It is also worth making sure `scripts/rebuild-deb.sh` is still working properly on buildkite as well. I don't think it's worth touching this script much, but maybe replacing the `CIRCLE_*` env vars with equivalent `BUILDKITE_*` ones.

+ coordinate with @0x0I  on getting the downstream data for the docker upload via the DOCKER_ENV as needed.

## Verification

You'll know if it works if you can `docker run -it ubuntu:18.04 bash` and successfully install coda via

```
echo "deb [trusted=yes] http://packages.o1test.net unstable main" | sudo tee /etc/apt/sources.list.d/coda.list
sudo apt-get update
sudo apt-get install -t unstable coda-testnet-postake-medium-curves=0.0.12-beta+406048-feature-bump-genesis-timestamp-3e9b174-PV48525e92
```

Then just run `coda version` and see if runs

**Comment by bkase** [comment]
Deb-related artifact step in buildkite  https://github.com/CodaProtocol/coda/blob/develop/buildkite/scripts/build-artifact.sh#L28
