### ISSUE TITLE
Monorepo fails submodule checkout on develop

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#5495]
I thought this was tracked already, but I couldn't find it just now.

On develop, it seems like the pipeline now _always_ fails until a manual retry on the monorepo step due to submodule updates.

```

Fetching submodule src/lib/zexe
--
  | fatal: unable to access 'https://github.com/o1-labs/zexe.git/': SSL certificate problem: unable to get local issuer certificate
  | fatal: unable to access 'https://github.com/o1-labs/zexe.git/': SSL certificate problem: unable to get local issuer certificate
  | Errors during submodule fetch:
  | src/lib/zexe
  | src/lib/zexe
  | 🚨 Error: The command exited with status 1
  |  
```

**Comment by 0x0I** [comment]
*Resolved* (as evidenced by [sequence of builds](https://buildkite.com/o-1-labs-2/coda/builds?branch=develop) during which submodules checked out successfully on develop) likely due to agent container image [change](https://github.com/CodaProtocol/coda-automation/commit/ea88742a7c2358c5083449b56dc5c2ce57947de9#diff-c8dd0de851b40328081ea6779d3842c9L49) *[alpine -> ubuntu]*.

**Comment by 0x0I** [comment]
Also added a [Nightly build](https://buildkite.com/o-1-labs-2/coda/settings/schedules/16d0ee61-9e40-4532-9467-41284d93cb26) of `develop` to help surface issues like this in the future.

**Comment by 0x0I** [comment]
re-opening as this seems to be occurring more frequently now (e.g. https://buildkite.com/o-1-labs-2/coda/builds/2278#87e76d3a-fdd8-4e44-8f44-65ca3cc978cf)

**Comment by mrmr1993** [comment]
This bug should happen deterministically, since the docker image never has ssl keys where git expects to find them, and the hack of disabling ssl is only for the coda repo (ie. not submodules).

I've opened #5892 to (in theory) fix this properly, by globally configuring git to point at the certificates in the docker image.
