### ISSUE TITLE
Logproc output JSON

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#747]

**Comment by cmr** [comment]
Mentoring instructions:

[`logproc`](https://github.com/CodaProtocol/coda/tree/master/src/app/logproc/src) is our tool for parsing, filtering, and pretty-printing the sexps that [`Logger`](https://github.com/CodaProtocol/coda/tree/master/src/lib/logger) outputs. Currently, it can only pretty print messages. It should also be able to output machine-readable JSON. There are two parts to this issue:

1. Add `Message.to_yojson` in `Logger`.

We use [`yojson`](https://github.com/mjambon/yojson) as our JSON library. [`ppx_deriving_yojson`](https://github.com/ocaml-ppx/ppx_deriving_yojson) makes it very easy to serialize values of a type. Unfortunately, unlike `sexp`, most modules don't already support JSON serialization. This makes it annoying to use for complex types. Fortunately, `Message.t` isn't too bad! The general pattern is this:

  1. Add `ppx_deriving_yojson` to the `preprocess` config in `jbuild` [eg](https://github.com/CodaProtocol/coda/blob/2b5302eb885b5bd9e699ceeb7d533aa180623c06/src/lib/cli_lib/jbuild#L17)
  2. Add `yojson` and `ppx_deriving_yojson.runtime` to the `libraries` config in `jbuild` [eg](https://github.com/CodaProtocol/coda/blob/2b5302eb885b5bd9e699ceeb7d533aa180623c06/src/lib/cli_lib/jbuild#L14)
  3. Make sure to add `-39` to the `-warn-error` config [eg](https://github.com/CodaProtocol/coda/blob/2b5302eb885b5bd9e699ceeb7d533aa180623c06/src/lib/cli_lib/jbuild#L6). `ppx_deriving_yojson` emits code with warnings.
  4. Add `[@@deriving yojson]` to `Message.t` in `logger.mli` [eg](https://github.com/CodaProtocol/coda/blob/master/src/lib/cli_lib/secret_box.mli#L1)
  5. In `logger.ml`, make a new type that is  `[@@deriving yojson]`. We'll be mapping to this type before using the derived `yojson` serialization. The idea is to replace the fields that don't already have `yojson` derivings with a `string` or some other type that `yojson` already knows how to handle. [eg](https://github.com/CodaProtocol/coda/blob/2b5302eb885b5bd9e699ceeb7d533aa180623c06/src/lib/cli_lib/secret_box.ml#L33)
  6. Implement `to_yojson` and `of_yojson` by mapping to/from this type [eg](https://github.com/CodaProtocol/coda/blob/master/src/lib/cli_lib/secret_box.ml#L55) and using this type's `to_yojson`.

Once that is done...

2. Use it in `logproc`

Add a boolean flag `-output-json`  (default false) to logproc [around here](https://github.com/CodaProtocol/coda/blob/2b5302eb885b5bd9e699ceeb7d533aa180623c06/src/app/logproc/src/logproc.ml#L79). Pass it through to the main function, and if it's true, instead of using `pretty_print_message`, use `Yojson.of_string (Message.to_yojson m)`.

**Comment by cmr** [comment]
We've replaced all the sexp stuff with JSON already.
